Algoritmo "antecessor"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jaison Costa
// Descrição   : Solicita um numero e descobre o antecessor
// Autor(a)    : Artur Queiroz
// Data atual  : 19/04/2026
Var
// Seção de Declarações das variáveis 
numero, antecessor : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero e descubra o seu antecessor : ")
leia(numero)
antecessor <- numero - 1
escreval ("O seu antecessor é : ", antecessor)

Fimalgoritmo