Algoritmo "area_retangulo"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jaison Costa
// Descrição    : Ler a base e a altura de um retangulo e calcular a area
// Autor(a)     : Artur Queiroz
// Data atual   : 19/04/2026

Var
// Seção de Declarações das variáveis
base, altura, area : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a base do retangulo: ")
leia(base)
escreva("Digite a altura do retangulo: ")
leia(altura)
area <- base * altura
escreval("A area do retangulo e: ", area)

Fimalgoritmo