Algoritmo "area_circulo"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Ler o raio de um circulo e calcular sua area
// Autor(a)     : Artur Queiroz
// Data atual   : 19/04/2026

Var
// Seção de Declarações das variáveis
raio, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o raio do circulo: ")
leia(raio)
area <- 3.14 * raio ^ 2
escreval("A area do circulo e: ", area)

Fimalgoritmo