Algoritmo "positivo_ou_negativo"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Ler um valor e informar se ele e positivo ou negativo
// Autor(a)     : Artur Queiroz
// Data atual   : 19/04/2026

Var
// Seção de Declarações das variáveis
valor : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um valor: ")
leia(valor)

se valor >= 0 entao
   escreval("O valor e positivo.")
senao
   escreval("O valor e negativo.")
fimse

Fimalgoritmo