Algoritmo "G7_Adicao_e_multiplicacao_entre_quatro_valores"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Mostrar as adições e multiplicações entre quatro números inteiros.
// Autor(a)     : Artur Queiroz
// Data atual   : 21/04/2026
Var
// Seção de Declarações das variáveis
a, b, c, d : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor de A: ")
leia(a)

escreva("Digite o valor de B: ")
leia(b)

escreva("Digite o valor de C: ")
leia(c)

escreva("Digite o valor de D: ")
leia(d)

escreval("A + B = ", a + b)
escreval("A + C = ", a + c)
escreval("A + D = ", a + d)
escreval("B + C = ", b + c)
escreval("B + D = ", b + d)
escreval("C + D = ", c + d)

escreval("A * B = ", a * b)
escreval("A * C = ", a * c)
escreval("A * D = ", a * d)
escreval("B * C = ", b * c)
escreval("B * D = ", b * d)
escreval("C * D = ", c * d)

Fimalgoritmo