Algoritmo "I7_Quadrado_da_diferenca_entre_dois_valores"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Calcular o quadrado da diferença entre dois valores inteiros.
// Autor(a)     : Artur Queiroz
// Data atual   : 21/04/2026
Var
// Seção de Declarações das variáveis
a, b, resultado : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor de A: ")
leia(a)

escreva("Digite o valor de B: ")
leia(b)

resultado <- (a - b) ^ 2

escreval("O quadrado da diferenca e: ", resultado)

Fimalgoritmo