Algoritmo "K4_Apresentar_valor_se_nao_for_maior_que_3"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Ler um valor inteiro e apresentá-lo somente se ele não for maior que 3.
// Autor(a)     : Artur Queiroz
// Data atual   : 22/04/2026
Var
// Seção de Declarações das variáveis
valor : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um valor inteiro: ")
leia(valor)

se valor <= 3 entao
   escreval("Valor lido: ", valor)
fimse

Fimalgoritmo