Algoritmo "L7_Soma_dos_quadrados_de_tres_valores"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Calcular a soma dos quadrados de três valores.
// Autor(a)     : Artur Queiroz
// Data atual   : 21/04/2026
Var
// Seção de Declarações das variáveis
a, b, c, soma : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor de A: ")
leia(a)

escreva("Digite o valor de B: ")
leia(b)

escreva("Digite o valor de C: ")
leia(c)

soma <- (a ^ 2) + (b ^ 2) + (c ^ 2)

escreval("A soma dos quadrados e: ", soma:0:2)

Fimalgoritmo