Algoritmo "M7_Quadrado_da_soma_de_tres_valores"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor    : Jailson Costa
// Descrição    : Calcular o quadrado da soma de três valores.
// Autor(a)     : Artur Queiroz
// Data atual   : 21/04/2026
Var
// Seção de Declarações das variáveis
a, b, c, resultado : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor de A: ")
leia(a)

escreva("Digite o valor de B: ")
leia(b)

escreva("Digite o valor de C: ")
leia(c)

resultado <- (a + b + c) ^ 2

escreval("O quadrado da soma e: ", resultado:0:2)

Fimalgoritmo