Algoritmo "areadocirculo"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jailson Costa
// Descrição   : Leia o valor do raio de um círculo e calcule sua área.
// Autor(a)    : Artur Queiroz
// Data atual  : 18/04/2026
Var
// Seção de Declarações das variáveis 
raio, area: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor do raio ")
leia (raio)
area <- 3.14 * raio ^ 2
escreval("O valor da area é do circulo é de: ", area)

Fimalgoritmo