Algoritmo "areaQuadrado"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jailson Costa
// Descrição   : Solicitar dois numero inteiros e calcular a soma da area.
// Autor(a)    : Artur Queiroz
// Data atual  : 18/04/2026
Var
// Seção de Declarações das variáveis 
lado, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual o valor do lado do quadrado? ")
leia(lado)
area <- lado * lado
escreval("A area do quadrado é ", area)

Fimalgoritmo