Algoritmo "areadoparalelogramo"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jailson Costa
// Descrição   : Leia a base e a altura de um paralelogramo e calcule sua área.
// Autor(a)    : Artur Queiroz
// Data atual  : 18/04/2026
Var
// Seção de Declarações das variáveis 
base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a base do paralelograma: ")
leia(base)
escreval("Digite a altura do paralelograma: ")
leia(altura)
area <- base * altura
escreva("A area do paralelogramo é de: ", area)

Fimalgoritmo