Algoritmo "comprimentodacircunferencia"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jailson Costa
// Descrição   : Leia o raio de um círculo e calcule o comprimento da circunferência.
// Autor(a)    : Artur Queiroz
// Data atual  : 18/04/2026
Var
// Seção de Declarações das variáveis 
raio, comprimento: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual é o valor do raio? ")
leia(raio)
comprimento <- 2*3.14*raio
escreval("O comprimento da circunferência é de ", comprimento)

Fimalgoritmo