Algoritmo "perimetrodoRetangulo"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jailson Costa
// Descrição   : Leia a base e a altura de um retângulo e calcule seu perímetro.
// Autor(a)    : Artur Queiroz
// Data atual  : 18/04/2026
Var
// Seção de Declarações das variáveis 
base, altura, perimetro : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a base do retângulo ")
leia (base)
escreva("Digite a base do retângulo ")
leia (altura)
perimetro <- 2*(base + altura)
escreval("O perímetro do retângulo é de : ", perimetro)
Fimalgoritmo