Algoritmo "perimetro"
// Disciplina   : [Lógica de Programação em VisualG]
// Professor   : Jailson Costa
// Descrição   : Leia o valor do lado de um quadrado e calcule o perímetro.
// Autor(a)    : Artur Queiroz
// Data atual  : 18/04/2026
Var
// Seção de Declarações das variáveis 
lado, perimetro : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor do lado do quadrado ")
leia(lado)
perimetro <- 4 * lado
escreval("O valor do périmetro é de : ", perimetro)

Fimalgoritmo